[stable-only] Cap cinder-tempest-plugin version for stable/victoria
We are capping stable/victoria testing with Tempest
26.1.0 (choosing 26.1.0 because of bug#1955418)

- https://review.opendev.org/c/openstack/devstack/+/843295

cinder-tempest-lvm-multibackend and other job failing with
incompatible Tempest 26.1.0 version with cinder-temepst-plugin master

AttributeError: 'SnapshotDataIntegrityTests' object has no attribute 'create_security_group'

- https://zuul.opendev.org/t/openstack/build/b86e63cc6cfd49dca96817b2ae7fdc71/logs

To fix that we need to use compatible cinder-tempest-plugin version for
Tempest 26.1.0, which is cinder-tempest-plugin 1.3.0.

Depends-On: https://review.opendev.org/c/openstack/devstack-plugin-ceph/+/843354
Depends-On: https://review.opendev.org/c/openstack/cinder/+/843092
Depends-On: https://review.opendev.org/c/openstack/devstack/+/843295

Change-Id: Ia6d0408280cb90da734ec505af7694fdea5333af