Fix for python3 compatability
In python3[1], the dict.keys() will return a dictionary view object,
which is dependent on original dictionary. Thus test in py3 will fail
inside the loop of dict.keys() with the error "RuntimeError: dictionary
changed size during iteration"[2]. Using list() will make a copy of keys
of the original dictionary instead and it will work for both py2 and
py3.

[1] https://docs.python.org/3.6/tutorial/datastructures.html#id4

[2] The error appears in cinder package building tests, extracted from
console log:

FAIL: cinder.tests.unit.test_volume_types.VolumeTypeTestCase.test_get_all_volume_types_az_not_shown
cinder.tests.unit.test_volume_types.VolumeTypeTestCase.test_get_all_volume_types_az_not_shown

Traceback (most recent call last):
  File "/build/cinder-13.0.5.10.g35d47c88d+bionic/cinder/tests/unit/test_volume_types.py", line 204, in test_get_all_volume_types_az_not_shown
    vol_types = volume_types.get_all_types(self.ctxt)
  File "/build/cinder-13.0.5.10.g35d47c88d+bionic/cinder/volume/volume_types.py", line 122, in get_all_types
    for vt in vol_types.keys():
RuntimeError: dictionary changed size during iteration

Change-Id: I47c8443a139e99cbd675ef6c987db7b12b031389